name = "hostelz"
version = "1.0.0"
target = "javascript"

[javascript]
runtime = "bun"
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
conversation = ">= 2.0.2 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
brioche = ">= 0.3.0 and < 1.0.0"
glanoid = ">= 1.0.1 and < 2.0.0"
gleam_crypto = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
bun_squirrel = { git = "https://github.com/ricardocasares/bun-squirrel", ref = "main" }
